/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StationsRouteImport } from './routes/stations'
import { Route as MediaRouteImport } from './routes/media'
import { Route as InvestorsRouteImport } from './routes/investors'
import { Route as FranchiseRouteImport } from './routes/franchise'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AcquisitionsRouteImport } from './routes/acquisitions'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MediaSlugRouteImport } from './routes/media.$slug'

const StationsRoute = StationsRouteImport.update({
  id: '/stations',
  path: '/stations',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorsRoute = InvestorsRouteImport.update({
  id: '/investors',
  path: '/investors',
  getParentRoute: () => rootRouteImport,
} as any)
const FranchiseRoute = FranchiseRouteImport.update({
  id: '/franchise',
  path: '/franchise',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AcquisitionsRoute = AcquisitionsRouteImport.update({
  id: '/acquisitions',
  path: '/acquisitions',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaSlugRoute = MediaSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MediaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/acquisitions': typeof AcquisitionsRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/franchise': typeof FranchiseRoute
  '/investors': typeof InvestorsRoute
  '/media': typeof MediaRouteWithChildren
  '/stations': typeof StationsRoute
  '/media/$slug': typeof MediaSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/acquisitions': typeof AcquisitionsRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/franchise': typeof FranchiseRoute
  '/investors': typeof InvestorsRoute
  '/media': typeof MediaRouteWithChildren
  '/stations': typeof StationsRoute
  '/media/$slug': typeof MediaSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/acquisitions': typeof AcquisitionsRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/franchise': typeof FranchiseRoute
  '/investors': typeof InvestorsRoute
  '/media': typeof MediaRouteWithChildren
  '/stations': typeof StationsRoute
  '/media/$slug': typeof MediaSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/acquisitions'
    | '/auth'
    | '/careers'
    | '/contact'
    | '/franchise'
    | '/investors'
    | '/media'
    | '/stations'
    | '/media/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/acquisitions'
    | '/auth'
    | '/careers'
    | '/contact'
    | '/franchise'
    | '/investors'
    | '/media'
    | '/stations'
    | '/media/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/acquisitions'
    | '/auth'
    | '/careers'
    | '/contact'
    | '/franchise'
    | '/investors'
    | '/media'
    | '/stations'
    | '/media/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AcquisitionsRoute: typeof AcquisitionsRoute
  AuthRoute: typeof AuthRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  FranchiseRoute: typeof FranchiseRoute
  InvestorsRoute: typeof InvestorsRoute
  MediaRoute: typeof MediaRouteWithChildren
  StationsRoute: typeof StationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stations': {
      id: '/stations'
      path: '/stations'
      fullPath: '/stations'
      preLoaderRoute: typeof StationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investors': {
      id: '/investors'
      path: '/investors'
      fullPath: '/investors'
      preLoaderRoute: typeof InvestorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/franchise': {
      id: '/franchise'
      path: '/franchise'
      fullPath: '/franchise'
      preLoaderRoute: typeof FranchiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acquisitions': {
      id: '/acquisitions'
      path: '/acquisitions'
      fullPath: '/acquisitions'
      preLoaderRoute: typeof AcquisitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/$slug': {
      id: '/media/$slug'
      path: '/$slug'
      fullPath: '/media/$slug'
      preLoaderRoute: typeof MediaSlugRouteImport
      parentRoute: typeof MediaRoute
    }
  }
}

interface MediaRouteChildren {
  MediaSlugRoute: typeof MediaSlugRoute
}

const MediaRouteChildren: MediaRouteChildren = {
  MediaSlugRoute: MediaSlugRoute,
}

const MediaRouteWithChildren = MediaRoute._addFileChildren(MediaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcquisitionsRoute: AcquisitionsRoute,
  AuthRoute: AuthRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  FranchiseRoute: FranchiseRoute,
  InvestorsRoute: InvestorsRoute,
  MediaRoute: MediaRouteWithChildren,
  StationsRoute: StationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
