/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StationsRouteImport } from './routes/stations'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ManagePortal9f4c2ab7RouteImport } from './routes/manage-portal-9f4c2ab7'
import { Route as InvestorsRouteImport } from './routes/investors'
import { Route as FranchiseRouteImport } from './routes/franchise'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AcquisitionsRouteImport } from './routes/acquisitions'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MediaIndexRouteImport } from './routes/media.index'
import { Route as ManagePortal9f4c2ab7IndexRouteImport } from './routes/manage-portal-9f4c2ab7.index'
import { Route as MediaSlugRouteImport } from './routes/media.$slug'
import { Route as ManagePortal9f4c2ab7LoginRouteImport } from './routes/manage-portal-9f4c2ab7_.login'
import { Route as ManagePortal9f4c2ab7SubmissionsRouteImport } from './routes/manage-portal-9f4c2ab7.submissions'
import { Route as ManagePortal9f4c2ab7StationsRouteImport } from './routes/manage-portal-9f4c2ab7.stations'
import { Route as ManagePortal9f4c2ab7NotificationsRouteImport } from './routes/manage-portal-9f4c2ab7.notifications'
import { Route as ManagePortal9f4c2ab7NewsRouteImport } from './routes/manage-portal-9f4c2ab7.news'
import { Route as ManagePortal9f4c2ab7ChatsRouteImport } from './routes/manage-portal-9f4c2ab7.chats'
import { Route as ManagePortal9f4c2ab7CareersRouteImport } from './routes/manage-portal-9f4c2ab7.careers'
import { Route as ManagePortal9f4c2ab7AuditRouteImport } from './routes/manage-portal-9f4c2ab7.audit'
import { Route as ManagePortal9f4c2ab7AbuseRouteImport } from './routes/manage-portal-9f4c2ab7.abuse'
import { Route as ApiPublicHooksProcessExportsRouteImport } from './routes/api/public/hooks/process-exports'

const StationsRoute = StationsRouteImport.update({
  id: '/stations',
  path: '/stations',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagePortal9f4c2ab7Route = ManagePortal9f4c2ab7RouteImport.update({
  id: '/manage-portal-9f4c2ab7',
  path: '/manage-portal-9f4c2ab7',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorsRoute = InvestorsRouteImport.update({
  id: '/investors',
  path: '/investors',
  getParentRoute: () => rootRouteImport,
} as any)
const FranchiseRoute = FranchiseRouteImport.update({
  id: '/franchise',
  path: '/franchise',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AcquisitionsRoute = AcquisitionsRouteImport.update({
  id: '/acquisitions',
  path: '/acquisitions',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaIndexRoute = MediaIndexRouteImport.update({
  id: '/media/',
  path: '/media/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagePortal9f4c2ab7IndexRoute =
  ManagePortal9f4c2ab7IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ManagePortal9f4c2ab7Route,
  } as any)
const MediaSlugRoute = MediaSlugRouteImport.update({
  id: '/media/$slug',
  path: '/media/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagePortal9f4c2ab7LoginRoute =
  ManagePortal9f4c2ab7LoginRouteImport.update({
    id: '/manage-portal-9f4c2ab7_/login',
    path: '/manage-portal-9f4c2ab7/login',
    getParentRoute: () => rootRouteImport,
  } as any)
const ManagePortal9f4c2ab7SubmissionsRoute =
  ManagePortal9f4c2ab7SubmissionsRouteImport.update({
    id: '/submissions',
    path: '/submissions',
    getParentRoute: () => ManagePortal9f4c2ab7Route,
  } as any)
const ManagePortal9f4c2ab7StationsRoute =
  ManagePortal9f4c2ab7StationsRouteImport.update({
    id: '/stations',
    path: '/stations',
    getParentRoute: () => ManagePortal9f4c2ab7Route,
  } as any)
const ManagePortal9f4c2ab7NotificationsRoute =
  ManagePortal9f4c2ab7NotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => ManagePortal9f4c2ab7Route,
  } as any)
const ManagePortal9f4c2ab7NewsRoute =
  ManagePortal9f4c2ab7NewsRouteImport.update({
    id: '/news',
    path: '/news',
    getParentRoute: () => ManagePortal9f4c2ab7Route,
  } as any)
const ManagePortal9f4c2ab7ChatsRoute =
  ManagePortal9f4c2ab7ChatsRouteImport.update({
    id: '/chats',
    path: '/chats',
    getParentRoute: () => ManagePortal9f4c2ab7Route,
  } as any)
const ManagePortal9f4c2ab7CareersRoute =
  ManagePortal9f4c2ab7CareersRouteImport.update({
    id: '/careers',
    path: '/careers',
    getParentRoute: () => ManagePortal9f4c2ab7Route,
  } as any)
const ManagePortal9f4c2ab7AuditRoute =
  ManagePortal9f4c2ab7AuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => ManagePortal9f4c2ab7Route,
  } as any)
const ManagePortal9f4c2ab7AbuseRoute =
  ManagePortal9f4c2ab7AbuseRouteImport.update({
    id: '/abuse',
    path: '/abuse',
    getParentRoute: () => ManagePortal9f4c2ab7Route,
  } as any)
const ApiPublicHooksProcessExportsRoute =
  ApiPublicHooksProcessExportsRouteImport.update({
    id: '/api/public/hooks/process-exports',
    path: '/api/public/hooks/process-exports',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/acquisitions': typeof AcquisitionsRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/franchise': typeof FranchiseRoute
  '/investors': typeof InvestorsRoute
  '/manage-portal-9f4c2ab7': typeof ManagePortal9f4c2ab7RouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stations': typeof StationsRoute
  '/manage-portal-9f4c2ab7/abuse': typeof ManagePortal9f4c2ab7AbuseRoute
  '/manage-portal-9f4c2ab7/audit': typeof ManagePortal9f4c2ab7AuditRoute
  '/manage-portal-9f4c2ab7/careers': typeof ManagePortal9f4c2ab7CareersRoute
  '/manage-portal-9f4c2ab7/chats': typeof ManagePortal9f4c2ab7ChatsRoute
  '/manage-portal-9f4c2ab7/news': typeof ManagePortal9f4c2ab7NewsRoute
  '/manage-portal-9f4c2ab7/notifications': typeof ManagePortal9f4c2ab7NotificationsRoute
  '/manage-portal-9f4c2ab7/stations': typeof ManagePortal9f4c2ab7StationsRoute
  '/manage-portal-9f4c2ab7/submissions': typeof ManagePortal9f4c2ab7SubmissionsRoute
  '/manage-portal-9f4c2ab7/login': typeof ManagePortal9f4c2ab7LoginRoute
  '/media/$slug': typeof MediaSlugRoute
  '/manage-portal-9f4c2ab7/': typeof ManagePortal9f4c2ab7IndexRoute
  '/media/': typeof MediaIndexRoute
  '/api/public/hooks/process-exports': typeof ApiPublicHooksProcessExportsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/acquisitions': typeof AcquisitionsRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/franchise': typeof FranchiseRoute
  '/investors': typeof InvestorsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stations': typeof StationsRoute
  '/manage-portal-9f4c2ab7/abuse': typeof ManagePortal9f4c2ab7AbuseRoute
  '/manage-portal-9f4c2ab7/audit': typeof ManagePortal9f4c2ab7AuditRoute
  '/manage-portal-9f4c2ab7/careers': typeof ManagePortal9f4c2ab7CareersRoute
  '/manage-portal-9f4c2ab7/chats': typeof ManagePortal9f4c2ab7ChatsRoute
  '/manage-portal-9f4c2ab7/news': typeof ManagePortal9f4c2ab7NewsRoute
  '/manage-portal-9f4c2ab7/notifications': typeof ManagePortal9f4c2ab7NotificationsRoute
  '/manage-portal-9f4c2ab7/stations': typeof ManagePortal9f4c2ab7StationsRoute
  '/manage-portal-9f4c2ab7/submissions': typeof ManagePortal9f4c2ab7SubmissionsRoute
  '/manage-portal-9f4c2ab7/login': typeof ManagePortal9f4c2ab7LoginRoute
  '/media/$slug': typeof MediaSlugRoute
  '/manage-portal-9f4c2ab7': typeof ManagePortal9f4c2ab7IndexRoute
  '/media': typeof MediaIndexRoute
  '/api/public/hooks/process-exports': typeof ApiPublicHooksProcessExportsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/acquisitions': typeof AcquisitionsRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/franchise': typeof FranchiseRoute
  '/investors': typeof InvestorsRoute
  '/manage-portal-9f4c2ab7': typeof ManagePortal9f4c2ab7RouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stations': typeof StationsRoute
  '/manage-portal-9f4c2ab7/abuse': typeof ManagePortal9f4c2ab7AbuseRoute
  '/manage-portal-9f4c2ab7/audit': typeof ManagePortal9f4c2ab7AuditRoute
  '/manage-portal-9f4c2ab7/careers': typeof ManagePortal9f4c2ab7CareersRoute
  '/manage-portal-9f4c2ab7/chats': typeof ManagePortal9f4c2ab7ChatsRoute
  '/manage-portal-9f4c2ab7/news': typeof ManagePortal9f4c2ab7NewsRoute
  '/manage-portal-9f4c2ab7/notifications': typeof ManagePortal9f4c2ab7NotificationsRoute
  '/manage-portal-9f4c2ab7/stations': typeof ManagePortal9f4c2ab7StationsRoute
  '/manage-portal-9f4c2ab7/submissions': typeof ManagePortal9f4c2ab7SubmissionsRoute
  '/manage-portal-9f4c2ab7_/login': typeof ManagePortal9f4c2ab7LoginRoute
  '/media/$slug': typeof MediaSlugRoute
  '/manage-portal-9f4c2ab7/': typeof ManagePortal9f4c2ab7IndexRoute
  '/media/': typeof MediaIndexRoute
  '/api/public/hooks/process-exports': typeof ApiPublicHooksProcessExportsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/acquisitions'
    | '/careers'
    | '/contact'
    | '/franchise'
    | '/investors'
    | '/manage-portal-9f4c2ab7'
    | '/sitemap.xml'
    | '/stations'
    | '/manage-portal-9f4c2ab7/abuse'
    | '/manage-portal-9f4c2ab7/audit'
    | '/manage-portal-9f4c2ab7/careers'
    | '/manage-portal-9f4c2ab7/chats'
    | '/manage-portal-9f4c2ab7/news'
    | '/manage-portal-9f4c2ab7/notifications'
    | '/manage-portal-9f4c2ab7/stations'
    | '/manage-portal-9f4c2ab7/submissions'
    | '/manage-portal-9f4c2ab7/login'
    | '/media/$slug'
    | '/manage-portal-9f4c2ab7/'
    | '/media/'
    | '/api/public/hooks/process-exports'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/acquisitions'
    | '/careers'
    | '/contact'
    | '/franchise'
    | '/investors'
    | '/sitemap.xml'
    | '/stations'
    | '/manage-portal-9f4c2ab7/abuse'
    | '/manage-portal-9f4c2ab7/audit'
    | '/manage-portal-9f4c2ab7/careers'
    | '/manage-portal-9f4c2ab7/chats'
    | '/manage-portal-9f4c2ab7/news'
    | '/manage-portal-9f4c2ab7/notifications'
    | '/manage-portal-9f4c2ab7/stations'
    | '/manage-portal-9f4c2ab7/submissions'
    | '/manage-portal-9f4c2ab7/login'
    | '/media/$slug'
    | '/manage-portal-9f4c2ab7'
    | '/media'
    | '/api/public/hooks/process-exports'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/acquisitions'
    | '/careers'
    | '/contact'
    | '/franchise'
    | '/investors'
    | '/manage-portal-9f4c2ab7'
    | '/sitemap.xml'
    | '/stations'
    | '/manage-portal-9f4c2ab7/abuse'
    | '/manage-portal-9f4c2ab7/audit'
    | '/manage-portal-9f4c2ab7/careers'
    | '/manage-portal-9f4c2ab7/chats'
    | '/manage-portal-9f4c2ab7/news'
    | '/manage-portal-9f4c2ab7/notifications'
    | '/manage-portal-9f4c2ab7/stations'
    | '/manage-portal-9f4c2ab7/submissions'
    | '/manage-portal-9f4c2ab7_/login'
    | '/media/$slug'
    | '/manage-portal-9f4c2ab7/'
    | '/media/'
    | '/api/public/hooks/process-exports'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AcquisitionsRoute: typeof AcquisitionsRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  FranchiseRoute: typeof FranchiseRoute
  InvestorsRoute: typeof InvestorsRoute
  ManagePortal9f4c2ab7Route: typeof ManagePortal9f4c2ab7RouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StationsRoute: typeof StationsRoute
  ManagePortal9f4c2ab7LoginRoute: typeof ManagePortal9f4c2ab7LoginRoute
  MediaSlugRoute: typeof MediaSlugRoute
  MediaIndexRoute: typeof MediaIndexRoute
  ApiPublicHooksProcessExportsRoute: typeof ApiPublicHooksProcessExportsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stations': {
      id: '/stations'
      path: '/stations'
      fullPath: '/stations'
      preLoaderRoute: typeof StationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage-portal-9f4c2ab7': {
      id: '/manage-portal-9f4c2ab7'
      path: '/manage-portal-9f4c2ab7'
      fullPath: '/manage-portal-9f4c2ab7'
      preLoaderRoute: typeof ManagePortal9f4c2ab7RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investors': {
      id: '/investors'
      path: '/investors'
      fullPath: '/investors'
      preLoaderRoute: typeof InvestorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/franchise': {
      id: '/franchise'
      path: '/franchise'
      fullPath: '/franchise'
      preLoaderRoute: typeof FranchiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acquisitions': {
      id: '/acquisitions'
      path: '/acquisitions'
      fullPath: '/acquisitions'
      preLoaderRoute: typeof AcquisitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/': {
      id: '/media/'
      path: '/media'
      fullPath: '/media/'
      preLoaderRoute: typeof MediaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage-portal-9f4c2ab7/': {
      id: '/manage-portal-9f4c2ab7/'
      path: '/'
      fullPath: '/manage-portal-9f4c2ab7/'
      preLoaderRoute: typeof ManagePortal9f4c2ab7IndexRouteImport
      parentRoute: typeof ManagePortal9f4c2ab7Route
    }
    '/media/$slug': {
      id: '/media/$slug'
      path: '/media/$slug'
      fullPath: '/media/$slug'
      preLoaderRoute: typeof MediaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage-portal-9f4c2ab7_/login': {
      id: '/manage-portal-9f4c2ab7_/login'
      path: '/manage-portal-9f4c2ab7/login'
      fullPath: '/manage-portal-9f4c2ab7/login'
      preLoaderRoute: typeof ManagePortal9f4c2ab7LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage-portal-9f4c2ab7/submissions': {
      id: '/manage-portal-9f4c2ab7/submissions'
      path: '/submissions'
      fullPath: '/manage-portal-9f4c2ab7/submissions'
      preLoaderRoute: typeof ManagePortal9f4c2ab7SubmissionsRouteImport
      parentRoute: typeof ManagePortal9f4c2ab7Route
    }
    '/manage-portal-9f4c2ab7/stations': {
      id: '/manage-portal-9f4c2ab7/stations'
      path: '/stations'
      fullPath: '/manage-portal-9f4c2ab7/stations'
      preLoaderRoute: typeof ManagePortal9f4c2ab7StationsRouteImport
      parentRoute: typeof ManagePortal9f4c2ab7Route
    }
    '/manage-portal-9f4c2ab7/notifications': {
      id: '/manage-portal-9f4c2ab7/notifications'
      path: '/notifications'
      fullPath: '/manage-portal-9f4c2ab7/notifications'
      preLoaderRoute: typeof ManagePortal9f4c2ab7NotificationsRouteImport
      parentRoute: typeof ManagePortal9f4c2ab7Route
    }
    '/manage-portal-9f4c2ab7/news': {
      id: '/manage-portal-9f4c2ab7/news'
      path: '/news'
      fullPath: '/manage-portal-9f4c2ab7/news'
      preLoaderRoute: typeof ManagePortal9f4c2ab7NewsRouteImport
      parentRoute: typeof ManagePortal9f4c2ab7Route
    }
    '/manage-portal-9f4c2ab7/chats': {
      id: '/manage-portal-9f4c2ab7/chats'
      path: '/chats'
      fullPath: '/manage-portal-9f4c2ab7/chats'
      preLoaderRoute: typeof ManagePortal9f4c2ab7ChatsRouteImport
      parentRoute: typeof ManagePortal9f4c2ab7Route
    }
    '/manage-portal-9f4c2ab7/careers': {
      id: '/manage-portal-9f4c2ab7/careers'
      path: '/careers'
      fullPath: '/manage-portal-9f4c2ab7/careers'
      preLoaderRoute: typeof ManagePortal9f4c2ab7CareersRouteImport
      parentRoute: typeof ManagePortal9f4c2ab7Route
    }
    '/manage-portal-9f4c2ab7/audit': {
      id: '/manage-portal-9f4c2ab7/audit'
      path: '/audit'
      fullPath: '/manage-portal-9f4c2ab7/audit'
      preLoaderRoute: typeof ManagePortal9f4c2ab7AuditRouteImport
      parentRoute: typeof ManagePortal9f4c2ab7Route
    }
    '/manage-portal-9f4c2ab7/abuse': {
      id: '/manage-portal-9f4c2ab7/abuse'
      path: '/abuse'
      fullPath: '/manage-portal-9f4c2ab7/abuse'
      preLoaderRoute: typeof ManagePortal9f4c2ab7AbuseRouteImport
      parentRoute: typeof ManagePortal9f4c2ab7Route
    }
    '/api/public/hooks/process-exports': {
      id: '/api/public/hooks/process-exports'
      path: '/api/public/hooks/process-exports'
      fullPath: '/api/public/hooks/process-exports'
      preLoaderRoute: typeof ApiPublicHooksProcessExportsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ManagePortal9f4c2ab7RouteChildren {
  ManagePortal9f4c2ab7AbuseRoute: typeof ManagePortal9f4c2ab7AbuseRoute
  ManagePortal9f4c2ab7AuditRoute: typeof ManagePortal9f4c2ab7AuditRoute
  ManagePortal9f4c2ab7CareersRoute: typeof ManagePortal9f4c2ab7CareersRoute
  ManagePortal9f4c2ab7ChatsRoute: typeof ManagePortal9f4c2ab7ChatsRoute
  ManagePortal9f4c2ab7NewsRoute: typeof ManagePortal9f4c2ab7NewsRoute
  ManagePortal9f4c2ab7NotificationsRoute: typeof ManagePortal9f4c2ab7NotificationsRoute
  ManagePortal9f4c2ab7StationsRoute: typeof ManagePortal9f4c2ab7StationsRoute
  ManagePortal9f4c2ab7SubmissionsRoute: typeof ManagePortal9f4c2ab7SubmissionsRoute
  ManagePortal9f4c2ab7IndexRoute: typeof ManagePortal9f4c2ab7IndexRoute
}

const ManagePortal9f4c2ab7RouteChildren: ManagePortal9f4c2ab7RouteChildren = {
  ManagePortal9f4c2ab7AbuseRoute: ManagePortal9f4c2ab7AbuseRoute,
  ManagePortal9f4c2ab7AuditRoute: ManagePortal9f4c2ab7AuditRoute,
  ManagePortal9f4c2ab7CareersRoute: ManagePortal9f4c2ab7CareersRoute,
  ManagePortal9f4c2ab7ChatsRoute: ManagePortal9f4c2ab7ChatsRoute,
  ManagePortal9f4c2ab7NewsRoute: ManagePortal9f4c2ab7NewsRoute,
  ManagePortal9f4c2ab7NotificationsRoute:
    ManagePortal9f4c2ab7NotificationsRoute,
  ManagePortal9f4c2ab7StationsRoute: ManagePortal9f4c2ab7StationsRoute,
  ManagePortal9f4c2ab7SubmissionsRoute: ManagePortal9f4c2ab7SubmissionsRoute,
  ManagePortal9f4c2ab7IndexRoute: ManagePortal9f4c2ab7IndexRoute,
}

const ManagePortal9f4c2ab7RouteWithChildren =
  ManagePortal9f4c2ab7Route._addFileChildren(ManagePortal9f4c2ab7RouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcquisitionsRoute: AcquisitionsRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  FranchiseRoute: FranchiseRoute,
  InvestorsRoute: InvestorsRoute,
  ManagePortal9f4c2ab7Route: ManagePortal9f4c2ab7RouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StationsRoute: StationsRoute,
  ManagePortal9f4c2ab7LoginRoute: ManagePortal9f4c2ab7LoginRoute,
  MediaSlugRoute: MediaSlugRoute,
  MediaIndexRoute: MediaIndexRoute,
  ApiPublicHooksProcessExportsRoute: ApiPublicHooksProcessExportsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
