/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StationsRouteImport } from './routes/stations'
import { Route as MediaRouteImport } from './routes/media'
import { Route as InvestorsRouteImport } from './routes/investors'
import { Route as FranchiseRouteImport } from './routes/franchise'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AcquisitionsRouteImport } from './routes/acquisitions'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as MediaSlugRouteImport } from './routes/media.$slug'
import { Route as AdminLoginRouteImport } from './routes/admin_.login'
import { Route as AdminSubmissionsRouteImport } from './routes/admin.submissions'
import { Route as AdminStationsRouteImport } from './routes/admin.stations'
import { Route as AdminNewsRouteImport } from './routes/admin.news'
import { Route as AdminChatsRouteImport } from './routes/admin.chats'
import { Route as AdminCareersRouteImport } from './routes/admin.careers'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminAbuseRouteImport } from './routes/admin.abuse'
import { Route as ApiPublicHooksProcessExportsRouteImport } from './routes/api/public/hooks/process-exports'

const StationsRoute = StationsRouteImport.update({
  id: '/stations',
  path: '/stations',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorsRoute = InvestorsRouteImport.update({
  id: '/investors',
  path: '/investors',
  getParentRoute: () => rootRouteImport,
} as any)
const FranchiseRoute = FranchiseRouteImport.update({
  id: '/franchise',
  path: '/franchise',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AcquisitionsRoute = AcquisitionsRouteImport.update({
  id: '/acquisitions',
  path: '/acquisitions',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const MediaSlugRoute = MediaSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MediaRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin_/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubmissionsRoute = AdminSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStationsRoute = AdminStationsRouteImport.update({
  id: '/stations',
  path: '/stations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsRoute = AdminNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChatsRoute = AdminChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCareersRoute = AdminCareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAbuseRoute = AdminAbuseRouteImport.update({
  id: '/abuse',
  path: '/abuse',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicHooksProcessExportsRoute =
  ApiPublicHooksProcessExportsRouteImport.update({
    id: '/api/public/hooks/process-exports',
    path: '/api/public/hooks/process-exports',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/acquisitions': typeof AcquisitionsRoute
  '/admin': typeof AdminRouteWithChildren
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/franchise': typeof FranchiseRoute
  '/investors': typeof InvestorsRoute
  '/media': typeof MediaRouteWithChildren
  '/stations': typeof StationsRoute
  '/admin/abuse': typeof AdminAbuseRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/careers': typeof AdminCareersRoute
  '/admin/chats': typeof AdminChatsRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/stations': typeof AdminStationsRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/login': typeof AdminLoginRoute
  '/media/$slug': typeof MediaSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/hooks/process-exports': typeof ApiPublicHooksProcessExportsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/acquisitions': typeof AcquisitionsRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/franchise': typeof FranchiseRoute
  '/investors': typeof InvestorsRoute
  '/media': typeof MediaRouteWithChildren
  '/stations': typeof StationsRoute
  '/admin/abuse': typeof AdminAbuseRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/careers': typeof AdminCareersRoute
  '/admin/chats': typeof AdminChatsRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/stations': typeof AdminStationsRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/login': typeof AdminLoginRoute
  '/media/$slug': typeof MediaSlugRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/hooks/process-exports': typeof ApiPublicHooksProcessExportsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/acquisitions': typeof AcquisitionsRoute
  '/admin': typeof AdminRouteWithChildren
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/franchise': typeof FranchiseRoute
  '/investors': typeof InvestorsRoute
  '/media': typeof MediaRouteWithChildren
  '/stations': typeof StationsRoute
  '/admin/abuse': typeof AdminAbuseRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/careers': typeof AdminCareersRoute
  '/admin/chats': typeof AdminChatsRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/stations': typeof AdminStationsRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin_/login': typeof AdminLoginRoute
  '/media/$slug': typeof MediaSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/hooks/process-exports': typeof ApiPublicHooksProcessExportsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/acquisitions'
    | '/admin'
    | '/careers'
    | '/contact'
    | '/franchise'
    | '/investors'
    | '/media'
    | '/stations'
    | '/admin/abuse'
    | '/admin/audit'
    | '/admin/careers'
    | '/admin/chats'
    | '/admin/news'
    | '/admin/stations'
    | '/admin/submissions'
    | '/admin/login'
    | '/media/$slug'
    | '/admin/'
    | '/api/public/hooks/process-exports'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/acquisitions'
    | '/careers'
    | '/contact'
    | '/franchise'
    | '/investors'
    | '/media'
    | '/stations'
    | '/admin/abuse'
    | '/admin/audit'
    | '/admin/careers'
    | '/admin/chats'
    | '/admin/news'
    | '/admin/stations'
    | '/admin/submissions'
    | '/admin/login'
    | '/media/$slug'
    | '/admin'
    | '/api/public/hooks/process-exports'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/acquisitions'
    | '/admin'
    | '/careers'
    | '/contact'
    | '/franchise'
    | '/investors'
    | '/media'
    | '/stations'
    | '/admin/abuse'
    | '/admin/audit'
    | '/admin/careers'
    | '/admin/chats'
    | '/admin/news'
    | '/admin/stations'
    | '/admin/submissions'
    | '/admin_/login'
    | '/media/$slug'
    | '/admin/'
    | '/api/public/hooks/process-exports'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AcquisitionsRoute: typeof AcquisitionsRoute
  AdminRoute: typeof AdminRouteWithChildren
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  FranchiseRoute: typeof FranchiseRoute
  InvestorsRoute: typeof InvestorsRoute
  MediaRoute: typeof MediaRouteWithChildren
  StationsRoute: typeof StationsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ApiPublicHooksProcessExportsRoute: typeof ApiPublicHooksProcessExportsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stations': {
      id: '/stations'
      path: '/stations'
      fullPath: '/stations'
      preLoaderRoute: typeof StationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investors': {
      id: '/investors'
      path: '/investors'
      fullPath: '/investors'
      preLoaderRoute: typeof InvestorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/franchise': {
      id: '/franchise'
      path: '/franchise'
      fullPath: '/franchise'
      preLoaderRoute: typeof FranchiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acquisitions': {
      id: '/acquisitions'
      path: '/acquisitions'
      fullPath: '/acquisitions'
      preLoaderRoute: typeof AcquisitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/media/$slug': {
      id: '/media/$slug'
      path: '/$slug'
      fullPath: '/media/$slug'
      preLoaderRoute: typeof MediaSlugRouteImport
      parentRoute: typeof MediaRoute
    }
    '/admin_/login': {
      id: '/admin_/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/submissions': {
      id: '/admin/submissions'
      path: '/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AdminSubmissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/stations': {
      id: '/admin/stations'
      path: '/stations'
      fullPath: '/admin/stations'
      preLoaderRoute: typeof AdminStationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/news': {
      id: '/admin/news'
      path: '/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AdminNewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/chats': {
      id: '/admin/chats'
      path: '/chats'
      fullPath: '/admin/chats'
      preLoaderRoute: typeof AdminChatsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/careers': {
      id: '/admin/careers'
      path: '/careers'
      fullPath: '/admin/careers'
      preLoaderRoute: typeof AdminCareersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/abuse': {
      id: '/admin/abuse'
      path: '/abuse'
      fullPath: '/admin/abuse'
      preLoaderRoute: typeof AdminAbuseRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/hooks/process-exports': {
      id: '/api/public/hooks/process-exports'
      path: '/api/public/hooks/process-exports'
      fullPath: '/api/public/hooks/process-exports'
      preLoaderRoute: typeof ApiPublicHooksProcessExportsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAbuseRoute: typeof AdminAbuseRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCareersRoute: typeof AdminCareersRoute
  AdminChatsRoute: typeof AdminChatsRoute
  AdminNewsRoute: typeof AdminNewsRoute
  AdminStationsRoute: typeof AdminStationsRoute
  AdminSubmissionsRoute: typeof AdminSubmissionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAbuseRoute: AdminAbuseRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminCareersRoute: AdminCareersRoute,
  AdminChatsRoute: AdminChatsRoute,
  AdminNewsRoute: AdminNewsRoute,
  AdminStationsRoute: AdminStationsRoute,
  AdminSubmissionsRoute: AdminSubmissionsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MediaRouteChildren {
  MediaSlugRoute: typeof MediaSlugRoute
}

const MediaRouteChildren: MediaRouteChildren = {
  MediaSlugRoute: MediaSlugRoute,
}

const MediaRouteWithChildren = MediaRoute._addFileChildren(MediaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcquisitionsRoute: AcquisitionsRoute,
  AdminRoute: AdminRouteWithChildren,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  FranchiseRoute: FranchiseRoute,
  InvestorsRoute: InvestorsRoute,
  MediaRoute: MediaRouteWithChildren,
  StationsRoute: StationsRoute,
  AdminLoginRoute: AdminLoginRoute,
  ApiPublicHooksProcessExportsRoute: ApiPublicHooksProcessExportsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
